version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: calculoimposto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - calculoimposto
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5433:5432"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  spring-app:
    build:
      context: ..
      dockerfile: podman/Podfile
    container_name: calculo-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/calculoimposto
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: on-failure
    networks:
      - calculoimposto
    ports:
      - "8080:8080"

networks:
  calculoimposto:

volumes:
  postgres-data: