name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Podman and Podman-Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y podman podman-compose

      - name: Set environment variables
        run: |
          echo "POSTGRES_DB=calculoimposto" >> .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/calculoimposto" >> .env
          echo "SPRING_DATASOURCE_USERNAME=postgres" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=postgres" >> .env

      - name: Start services with Podman-Compose
        run: |
          export COMPOSE_FILE=podman-compose.yaml
          podman-compose up -d

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            podman exec postgres-container pg_isready -U postgres -d calculoimposto && echo "PostgreSQL is ready" && exit 0
            echo "Waiting for PostgreSQL..."
            sleep 5
          done
          echo "PostgreSQL failed to start" && exit 1

      - name: Run tests
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn test