name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Podman and Podman-Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y podman podman-compose

      - name: Start services with Podman-Compose
        run: |
          podman-compose --env-file .env.compose up -d

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            podman exec postgres-container pg_isready -U postgres -d calculoimposto && echo "PostgreSQL is ready" && exit 0
            echo "Waiting for PostgreSQL..."
            sleep 5
          done
          echo "PostgreSQL failed to start" && exit 1

      - name: Run tests
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn test